language: python
sudo: false
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
python:
  - 2.7
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - rm .installed.cfg
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
install:
  - python bootstrap-buildout.py -c travis.cfg
  - bin/buildout -Nc travis.cfg
script:
  - bin/test
after_success:
  - bin/createcoverage
  - pip install coverage==3.7 coveralls
  - coveralls

notifications:
  email:
    - nguyen@plone.org
